# Generated by Django 4.1 on 2024-01-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinate",
            name="outer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clothes.item"
            ),
        ),
    ]
