# Generated by Django 5.0.1 on 2024-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0002_alter_coordinate_outer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinate",
            name="outer",
            field=models.FileField(upload_to="picture/"),
        ),
    ]
