# Generated by Django 5.0.1 on 2024-01-22 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0003_alter_coordinate_outer"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="coordinate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clothes.coordinate",
            ),
        ),
    ]
