# Generated by Django 5.0.1 on 2024-01-23 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0004_item_coordinate"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinate",
            name="inner",
            field=models.FileField(default="", upload_to="picture/"),
        ),
        migrations.AddField(
            model_name="coordinate",
            name="pants",
            field=models.FileField(default="", upload_to="picture/"),
        ),
        migrations.AddField(
            model_name="coordinate",
            name="shoes",
            field=models.FileField(default="", upload_to="picture/"),
        ),
        migrations.AddField(
            model_name="item",
            name="inner",
            field=models.FileField(default="", upload_to="picture/"),
        ),
        migrations.AddField(
            model_name="item",
            name="pants",
            field=models.FileField(default="", upload_to="picture/"),
        ),
        migrations.AddField(
            model_name="item",
            name="shoes",
            field=models.FileField(default="", upload_to="picture/"),
        ),
        migrations.AlterField(
            model_name="coordinate",
            name="create_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="coordinate",
            name="update_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="item",
            name="create_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="item",
            name="update_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
