# Generated by Django 5.0.1 on 2024-01-29 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0005_coordinate_inner_coordinate_pants_coordinate_shoes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinate",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coordinate",
            name="outer",
            field=models.FileField(default="", upload_to="picture/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="outer",
            field=models.FileField(default="", upload_to="picture/"),
        ),
    ]
