# Generated by Django 5.0.1 on 2024-02-01 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0006_coordinate_user_item_user_alter_coordinate_outer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
