# Generated by Django 5.0.1 on 2024-02-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0011_outer_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outer",
            name="favorite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorited_by",
                to="clothes.outer",
            ),
        ),
    ]
