# Generated by Django 5.0.1 on 2024-02-06 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0012_alter_outer_favorite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outer",
            name="favorite",
        ),
    ]
