# Generated by Django 5.0.1 on 2024-02-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0015_remove_outer_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="outer",
            name="favorite",
            field=models.FileField(default="", upload_to="picture/"),
        ),
    ]
