# Generated by Django 5.0.1 on 2024-02-07 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0018_rename_outer_favorite_outer1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="outer1",
            new_name="outerr",
        ),
    ]
