# Generated by Django 5.0.1 on 2024-02-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0019_rename_outer1_favorite_outerr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="outerr",
        ),
        migrations.AddField(
            model_name="favorite",
            name="outer_image",
            field=models.FileField(default="", upload_to="favorite_picture/"),
        ),
    ]
