# Generated by Django 5.0.1 on 2024-02-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0020_remove_favorite_outerr_favorite_outer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="outer_image",
            field=models.FileField(default="", upload_to="picture/"),
        ),
    ]
