# Generated by Django 5.0.1 on 2024-02-07 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0021_alter_favorite_outer_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="outer_image",
            new_name="outer",
        ),
    ]
